### ISSUE TITLE
VPN非接続時のresumeではproxyをstartさせないでほしい

### ISSUE THREAD

**Issue by kosaki** [ipponshimeji/MAPE#1]
現状、Windowsがresumeするタイミングで常にproxyがstartするような挙動をしめします。
しかしながら、suspend時にproxyが止まっていた時、具体的なシチュエーションとしては
出先でVPN非接続で使っていた時は、Proxyをstartしてほしくありません。
社内proxy serverにunreachableなので、ブラウザがまともに動かなくなります。

・resume時にactual proxyがreachableかどうかをチェックする、または
・suspend時にproxyがstartしていたかどうかを覚えておく

のどちらかが実装されるとうれしいです。

**Comment by ipponshimeji** [comment]
「Windowsがresumeするタイミングで常にproxyがstartするような挙動をしめす」のは単純にバグです。「suspend時にproxyがstartしていたかどうかを覚えてお」いたのに、resume時にそれを反映していませんでした。これは即修正しました。1.0.14.0で直っています。

一方、Actual Proxyを明に指定している場合、現状それがreachableかどうかチェックしていないのですが、確かにチェックすべきです。これも直しますが、少々お待ちください。プロキシの到達性って何で確認するのがいいかちと考えます。

**Comment by ipponshimeji** [comment]
中継開始時に実際のプロキシへの接続性を確認するようにしました。
1.0.15.0以降をお使いください。
