### ISSUE TITLE
GUI版の起動時に自動で中継を開始することはできますか？

### ISSUE THREAD

**Issue by kai2nenobu** [ipponshimeji/MAPE#3]
Windows起動時に自動でmapeguiを起動し、特に操作することなく認証プロキシへ中継できる状態にしたいです。ただmapeguiを起動しただけでは自動で中継を開始されず、タスクトレイの `中継を開始する` を押下しないと中継が開始されないのが現状です。

自動で中継を開始する設定項目やコマンドラインオプションはありますか？

**Comment by ipponshimeji** [comment]
今はありません。が、簡単にできると思うので、週末に実装してみます。

**Comment by ipponshimeji** [comment]
実装しました。1.0.20.0をお使いください。

コマンドラインで/Startを指定すると、起動後自動的に中継を開始します。
設定ファイルにも記述できます。設定ファイルの`GUI`オブジェクトに`"Start": true`を追加すれば/Startを指定しなくても起動後に中継を開始するようになります。詳細はドキュメントの「
設定ファイルリファレンス」を参照してください。
設定ウィンドウに項目を追加するかどうか迷いましたが、まあ、基本的にこの動作はオプションで指定すべきだろうと思ったので、追加していません。

中継開始はシステムサスペンドからの復帰時の中継再開処理を流用しています。ただし、中継再開と/Startによる開始では以下の点が異なります。

- 「初期遅延」は入れません。直ちに中継開始を試みます。
- 「試行回数」が0の場合は1とみなします。（つまり、最低1回は中継開始を試みます）

システム復帰時の中継再開のための設定値の「試行回数」「試行間隔」を流用していますので、もしシステム起動直後にシステムのプロキシ設定が安定せずに中継に失敗するような場合は、設定の「その他」-「システムがスリープ/休止から復帰した際の中継再開」の「試行回数」「試行間隔」を調整してうまくリトライさせてください。
まあ見たところ、レジュームと違って、システム起動後のスタートアップ開始時にはシステムプロキシ設定は安定しているようなので、とくに心配ないとは思いますが。

**Comment by kai2nenobu** [comment]
迅速な対応ありがとうございます。バッチリ起動と同時に中継開始ができるようになりました。
