### ISSUE TITLE
MAPE GUIの実行が出来なくなりました

### ISSUE THREAD

**Issue by HataKo1** [ipponshimeji/MAPE#6]
長らく愛用させていただいておりますが、PCが新しい機種となり、MAPE GUIを実行すると「指定された状態で使用するには無効なキーです。」のエラーダイアログが表示されて起動することが出来なくなりました。

Windowsの設定状態が異なるのだと思いますが、対策方法が分かりましたら嬉しいです。

![image](https://github.com/ipponshimeji/MAPE/assets/51699314/fef76af4-c0c4-4c72-8512-9de35b0f15f9)

**Comment by ipponshimeji** [comment]
エラーメッセージからすると、暗号化している認証プロキシのパスワードが復号できなくなっているようです。
パスワードの暗号化は特定のPC上のユーザーに紐づけられており、設定ファイルをコピーして別のPCやユーザーアカウントにコピーしても利用できないようになっています。
設定を以前のPCから引き継がれたのではないでしょうか。

対応策としては、設定ファイルを作り直し、認証プロキシのパスワードを設定し直すことになります。

1. 設定ファイルをバックアップします。
    - 設定ファイルは`%LOCALAPPDATA%\MAPE\Settings.json`です。
      （通常、実際のパスは`C:\Users\<ユーザー名>\AppData\Local\MAPE\Settings.json`）になります。
1. 以下のどちらかの手順を実施してください。
    * JSON形式をご存じの場合:
        - 設定ファイルの中身の`Credentials`プロパティの値を空配列にします。
          （JSONの形式を壊さないようにご注意ください）
    * JSON形式に詳しくない場合:
        - 設定ファイルを削除してください。
        - 次にMAPE GUIを起動した際に初期設定画面が出ますので、設定をやり直してください。
          （その際に設定ファイルのバックアップを参考にすることができるでしょう）
1. 次回MAPEを起動後、最初に認証プロキシにアクセスした際にパスワードの入力が求められます。
   そこで入力したパスワードは現在の環境に合わせて暗号化されて設定ファイルに保存されます。

**Comment by HataKo1** [comment]
ご丁寧なご回答痛み入ります。

ご高察のとおり、新しいPCへのデータ移行でユーザアカウントフォルダのコピーを行っておりました。
ご案内に従い、%LOCALAPPDATA%\MAPE\Settings.jsonをバックアップ後削除し、MAPE GUIを起動後バックアップファイルを参考に設定を行ったところ、利用可能な状態に戻りました。

心より感謝いたします。

**Comment by ipponshimeji** [comment]
解決してよかったです。Issueはクローズしますね。
